#!/bin/bash

export PATH=$PATH:/usr/local/share/python

# The next line updates PATH for the Google Cloud SDK.
#source /Users/djoshea/extern/google-cloud-sdk/path.bash.inc

# The next line enables bash completion for gcloud.
source /Users/djoshea/extern/google-cloud-sdk/completion.zsh.inc


